name = "imgbed"
compatibility_date = "2023-12-01"
pages_build_output_dir = "dist"

[env.production]
name = "imgbed-production"
[env.production.vars]
ENVIRONMENT = "production"

[env.preview]
name = "imgbed-preview"
[env.preview.vars]
ENVIRONMENT = "preview"
